name: we_pei_yang_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# 请保证 'package:we_pei_yang_flutter/commons/environment/config.dart'
# 中的 version 和 versionCode 保持一致
version: 4.2.9+107

# 打包代码 flutter build apk --split-per-abi
# flutter build apk --target-platform android-arm,android-arm64 --split-per-abi

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  async: ^2.5.0
  badges: ^2.0.1
  connectivity: ^3.0.6
  dio: ^4.0.0
  dotted_border: ^2.0.0+1
  fluttertoast: ^8.0.8
  flutter_html: ^2.0.0
  flutter_markdown: ^0.6.9+1
  flutter_rating_bar: ^4.0.0
  flutter_svg: ^0.22.0
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^4.0.4
  simple_url_preview: ^3.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.1
  http_parser: ^4.0.0
  image_cropper: 1.5.0
  image_picker: ^0.8.4+1
  like_button: ^2.0.3
  linkfy_text: ^1.1.5
  intl: ^0.17.0
  location_permissions: ^4.0.1
  package_info: ^2.0.2
  path_provider: ^2.0.4
  photo_view: ^0.13.0
  provider: ^6.0.1
  pull_to_refresh: ^2.0.0
  screenshot: ^1.2.3  # 还没用到
  shared_preferences: ^2.0.7
  simple_html_css: ^3.0.1
  table_calendar: 3.0.2
  transparent_image: ^1.0.0
  url_launcher: ^6.0.10
  webview_flutter: ^2.0.13
  wechat_assets_picker: ^6.2.0
  weathers: ^1.0.2
  extended_tabs: ^2.3.0
  extended_image: ^4.0.0
  flutter_native_image: ^0.0.6+1
  flutter_smart_dialog: ^3.3.5
  # 升级到flutter 2.2.1后，checkbox自带shape属性
  circular_check_box: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
#  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/account/
    - assets/svg_pics/
    - assets/svg_pics/lake_butt_icons/
    - assets/images/account/1.5x/
    - assets/images/account/2.0x/
    - assets/images/account/3.0x/
    - assets/images/account/4.0x/
    - assets/images/lake_butt_icons/
    - assets/images/begonia/
    - privacy/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Alternates-Bold.ttf

    - family: Aspira
      fonts:
        - asset: assets/fonts/ASPIRA WIDE W01 BOLD.ttf

    - family: Texta
      fonts:
        - asset: assets/fonts/Texta Narrow W00 Thin.ttf

    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-HeavyItalic-8.otf

    - family: Bauhaus
      fonts:
        - asset: assets/fonts/Bauhaus-Bold-Italic_6276.ttf
          style: italic

    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf

flutter_intl:
  enabled: true
